In [1]:
#import libraries 
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 

In [10]:
df = pd.read_csv("siFKtk.csv")

In [11]:
df.head(6)

Education  JoiningYear       City  PaymentTier  Age  Gender EverBenched  \
0  Bachelors         2017  Bangalore            3   34    Male          No   
1  Bachelors         2013       Pune            1   28  Female          No   
2  Bachelors         2014  New Delhi            3   38  Female          No   
3    Masters         2016  Bangalore            3   27    Male          No   
4    Masters         2017       Pune            3   24    Male         Yes   
5  Bachelors         2016  Bangalore            3   22    Male          No   

   ExperienceInCurrentDomain  LeaveOrNot  
0                          0           0  
1                          3           1  
2                          2           0  
3                          5           1  
4                          2           1  
5                          0           0

In [12]:
df.tail()

Education  JoiningYear       City  PaymentTier  Age  Gender EverBenched  \
4648  Bachelors         2013  Bangalore            3   26  Female          No   
4649    Masters         2013       Pune            2   37    Male          No   
4650    Masters         2018  New Delhi            3   27    Male          No   
4651  Bachelors         2012  Bangalore            3   30    Male         Yes   
4652  Bachelors         2015  Bangalore            3   33    Male         Yes   

      ExperienceInCurrentDomain  LeaveOrNot  
4648                          4           0  
4649                          2           1  
4650                          5           1  
4651                          2           0  
4652                          4           0

In [13]:
df.isnull().sum()

Education                    0
JoiningYear                  0
City                         0
PaymentTier                  0
Age                          0
Gender                       0
EverBenched                  0
ExperienceInCurrentDomain    0
LeaveOrNot                   0
dtype: int64

In [14]:
df.shape

(4653, 9)

In [15]:
df.columns

Index(['Education', 'JoiningYear', 'City', 'PaymentTier', 'Age', 'Gender',
       'EverBenched', 'ExperienceInCurrentDomain', 'LeaveOrNot'],
      dtype='object')

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4653 entries, 0 to 4652
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype 
---  ------                     --------------  ----- 
 0   Education                  4653 non-null   object
 1   JoiningYear                4653 non-null   int64 
 2   City                       4653 non-null   object
 3   PaymentTier                4653 non-null   int64 
 4   Age                        4653 non-null   int64 
 5   Gender                     4653 non-null   object
 6   EverBenched                4653 non-null   object
 7   ExperienceInCurrentDomain  4653 non-null   int64 
 8   LeaveOrNot                 4653 non-null   int64 
dtypes: int64(5), object(4)
memory usage: 327.3+ KB


In [17]:
df['Education'].unique()

array(['Bachelors', 'Masters', 'PHD'], dtype=object)

In [18]:
df['City'].unique()

array(['Bangalore', 'Pune', 'New Delhi'], dtype=object)

In [19]:
df['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [20]:
df['EverBenched'].unique()

array(['No', 'Yes'], dtype=object)

In [21]:
encoded = pd.get_dummies(df,dtype="int")

In [22]:
encoded

JoiningYear  PaymentTier  Age  ExperienceInCurrentDomain  LeaveOrNot  \
0            2017            3   34                          0           0   
1            2013            1   28                          3           1   
2            2014            3   38                          2           0   
3            2016            3   27                          5           1   
4            2017            3   24                          2           1   
...           ...          ...  ...                        ...         ...   
4648         2013            3   26                          4           0   
4649         2013            2   37                          2           1   
4650         2018            3   27                          5           1   
4651         2012            3   30                          2           0   
4652         2015            3   33                          4           0   

      Education_Bachelors  Education_Masters  Education_PHD  City_Bangalore  \
0                       1                  0              0               1   
1                       1                  0              0               0   
2                       1                  0              0               0   
3                       0                  1              0               1   
4                       0                  1              0               0   
...                   ...                ...            ...             ...   
4648                    1                  0              0               1   
4649                    0                  1              0               0   
4650                    0                  1              0               0   
4651                    1                  0              0               1   
4652                    1                  0              0               1   

      City_New Delhi  City_Pune  Gender_Female  Gender_Male  EverBenched_No  \
0                  0          0              0            1               1   
1                  0          1              1            0               1   
2                  1          0              1            0               1   
3                  0          0              0            1               1   
4                  0          1              0            1               0   
...              ...        ...            ...          ...             ...   
4648               0          0              1            0               1   
4649               0          1              0            1               1   
4650               1          0              0            1               1   
4651               0          0              0            1               0   
4652               0          0              0            1               0   

      EverBenched_Yes  
0                   0  
1                   0  
2                   0  
3                   0  
4                   1  
...               ...  
4648                0  
4649                0  
4650                0  
4651                1  
4652                1  

[4653 rows x 15 columns]

In [40]:
X = encoded.drop("LeaveOrNot", axis=1)
y = encoded["LeaveOrNot"]

In [41]:
from sklearn.model_selection import train_test_split

In [42]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [43]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()

In [44]:
lr.fit(X_train,y_train)

C:\Users\USER-PC\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [46]:
lr.score(X_test,y_test)

0.7422126745435016

In [ ]:
DECISION TREE

In [47]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# 1. Model create and fit
dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train, y_train)

# 2. Predict
y_pred = dt.predict(X_test)

# 3. Evaluation
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))


Accuracy: 0.8431793770139635

Confusion Matrix:
 [[552  58]
 [ 88 233]]

Classification Report:
               precision    recall  f1-score   support

           0       0.86      0.90      0.88       610
           1       0.80      0.73      0.76       321

    accuracy                           0.84       931
   macro avg       0.83      0.82      0.82       931
weighted avg       0.84      0.84      0.84       931



In [ ]:
RANDOM FOREST 

In [48]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# 1. Model create and fit
rf = RandomForestClassifier(random_state=42)
rf.fit(X_train, y_train)

# 2. Predict
y_pred = rf.predict(X_test)

# 3. Evaluation
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))


Accuracy: 0.8528464017185822

Confusion Matrix:
 [[559  51]
 [ 86 235]]

Classification Report:
               precision    recall  f1-score   support

           0       0.87      0.92      0.89       610
           1       0.82      0.73      0.77       321

    accuracy                           0.85       931
   macro avg       0.84      0.82      0.83       931
weighted avg       0.85      0.85      0.85       931



In [ ]:
SUPPORT VECTOR MACHINE 

In [49]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# 1. Model create and fit
svm = SVC(kernel='rbf', C=1.0, gamma='scale')  # Default RBF kernel
svm.fit(X_train, y_train)

# 2. Predict
y_pred = svm.predict(X_test)

# 3. Evaluation
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))


Accuracy: 0.6552094522019334

Confusion Matrix:
 [[610   0]
 [321   0]]

Classification Report:
               precision    recall  f1-score   support

           0       0.66      1.00      0.79       610
           1       0.00      0.00      0.00       321

    accuracy                           0.66       931
   macro avg       0.33      0.50      0.40       931
weighted avg       0.43      0.66      0.52       931



C:\Users\USER-PC\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\USER-PC\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\USER-PC\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
